### ISSUE TITLE
bug:snake dies if you try to walk backwards

### ISSUE THREAD

**Issue by vzsoares** [ThiagoPereiraSje/jogo-cobrinha#1]
bug:if the snake have more than 1 tile of length and you try to walk to the opposite direction (example: if its going to west and you click east) you die

expected behavior: nothing should happen

**Comment by ThiagoPereiraSje** [comment]
It's not really a bug, what happens is that when walking backwards, the snake hits itself.
This will depend on what was requested.

**Comment by ThiagoPereiraSje** [comment]
Boa tarde Zenha tudo blz? acho que não é bem um bug, o que acontece é que a
cobrinha se acerta.

Em qua., 6 de abr. de 2022 às 13:47, Vinicius Zenha <
***@***.***> escreveu:

**Comment by vzsoares** [comment]
Pois é mas em jogos como esse online por exemplo o behavior costuma ser como descrevi acima, quando eu fiz esse exercício eu notei esse behavior e decidi deixar como os outros ,porém claro fica a seu critério 😉
